/* Generated by scripts/gen_cpuinfo_flags.py from Linux kernel source */
/* kernel: /path/to/linux */
/* Do not edit manually. Regenerate with: python3 scripts/gen_cpuinfo_flags.py --kernel /path/to/linux */
#pragma once

struct cpuid_flag {
    unsigned leaf;
    unsigned subleaf;
    unsigned reg; /* 0=EAX 1=EBX 2=ECX 3=EDX */
    unsigned bit;
    const char *name;
};

static const struct cpuid_flag cpuid_flags[] = {
    {0x00000001, 0, 3,  0, "fpu"}, /* X86_FEATURE_FPU Onboard FPU */
    {0x00000001, 0, 3,  1, "vme"}, /* X86_FEATURE_VME Virtual Mode Extensions */
    {0x00000001, 0, 3,  2, "de"}, /* X86_FEATURE_DE Debugging Extensions */
    {0x00000001, 0, 3,  3, "pse"}, /* X86_FEATURE_PSE Page Size Extensions */
    {0x00000001, 0, 3,  4, "tsc"}, /* X86_FEATURE_TSC Time Stamp Counter */
    {0x00000001, 0, 3,  5, "msr"}, /* X86_FEATURE_MSR Model-Specific Registers */
    {0x00000001, 0, 3,  6, "pae"}, /* X86_FEATURE_PAE Physical Address Extensions */
    {0x00000001, 0, 3,  7, "mce"}, /* X86_FEATURE_MCE Machine Check Exception */
    {0x00000001, 0, 3,  8, "cx8"}, /* X86_FEATURE_CX8 CMPXCHG8 instruction */
    {0x00000001, 0, 3,  9, "apic"}, /* X86_FEATURE_APIC Onboard APIC */
    {0x00000001, 0, 3, 11, "sep"}, /* X86_FEATURE_SEP SYSENTER/SYSEXIT */
    {0x00000001, 0, 3, 12, "mtrr"}, /* X86_FEATURE_MTRR Memory Type Range Registers */
    {0x00000001, 0, 3, 13, "pge"}, /* X86_FEATURE_PGE Page Global Enable */
    {0x00000001, 0, 3, 14, "mca"}, /* X86_FEATURE_MCA Machine Check Architecture */
    {0x00000001, 0, 3, 15, "cmov"}, /* X86_FEATURE_CMOV CMOV instructions (plus FCMOVcc, FCOMI with FPU) */
    {0x00000001, 0, 3, 16, "pat"}, /* X86_FEATURE_PAT Page Attribute Table */
    {0x00000001, 0, 3, 17, "pse36"}, /* X86_FEATURE_PSE36 36-bit PSEs */
    {0x00000001, 0, 3, 18, "pn"}, /* X86_FEATURE_PN Processor serial number */
    {0x00000001, 0, 3, 19, "clflush"}, /* X86_FEATURE_CLFLUSH CLFLUSH instruction */
    {0x00000001, 0, 3, 21, "dts"}, /* X86_FEATURE_DS Debug Store */
    {0x00000001, 0, 3, 22, "acpi"}, /* X86_FEATURE_ACPI ACPI via MSR */
    {0x00000001, 0, 3, 23, "mmx"}, /* X86_FEATURE_MMX Multimedia Extensions */
    {0x00000001, 0, 3, 24, "fxsr"}, /* X86_FEATURE_FXSR FXSAVE/FXRSTOR, CR4.OSFXSR */
    {0x00000001, 0, 3, 25, "sse"}, /* X86_FEATURE_XMM sse */
    {0x00000001, 0, 3, 26, "sse2"}, /* X86_FEATURE_XMM2 sse2 */
    {0x00000001, 0, 3, 27, "ss"}, /* X86_FEATURE_SELFSNOOP CPU self snoop */
    {0x00000001, 0, 3, 28, "ht"}, /* X86_FEATURE_HT Hyper-Threading */
    {0x00000001, 0, 3, 29, "tm"}, /* X86_FEATURE_ACC Automatic clock control */
    {0x00000001, 0, 3, 30, "ia64"}, /* X86_FEATURE_IA64 IA-64 processor */
    {0x00000001, 0, 3, 31, "pbe"}, /* X86_FEATURE_PBE Pending Break Enable */
    {0x80000001, 0, 3, 11, "syscall"}, /* X86_FEATURE_SYSCALL SYSCALL/SYSRET */
    {0x80000001, 0, 3, 19, "mp"}, /* X86_FEATURE_MP MP Capable */
    {0x80000001, 0, 3, 20, "nx"}, /* X86_FEATURE_NX Execute Disable */
    {0x80000001, 0, 3, 22, "mmxext"}, /* X86_FEATURE_MMXEXT AMD MMX extensions */
    {0x80000001, 0, 3, 25, "fxsr_opt"}, /* X86_FEATURE_FXSR_OPT FXSAVE/FXRSTOR optimizations */
    {0x80000001, 0, 3, 26, "pdpe1gb"}, /* X86_FEATURE_GBPAGES GB pages */
    {0x80000001, 0, 3, 27, "rdtscp"}, /* X86_FEATURE_RDTSCP RDTSCP */
    {0x80000001, 0, 3, 29, "lm"}, /* X86_FEATURE_LM Long Mode (x86-64, 64-bit support) */
    {0x80000001, 0, 3, 30, "3dnowext"}, /* X86_FEATURE_3DNOWEXT AMD 3DNow extensions */
    {0x80000001, 0, 3, 31, "3dnow"}, /* X86_FEATURE_3DNOW 3DNow */
    {0x80860001, 0, 3,  0, "recovery"}, /* X86_FEATURE_RECOVERY CPU in recovery mode */
    {0x80860001, 0, 3,  1, "longrun"}, /* X86_FEATURE_LONGRUN Longrun power control */
    {0x80860001, 0, 3,  3, "lrti"}, /* X86_FEATURE_LRTI LongRun table interface */
    {0x80000022, 0, 0,  1, "amd_lbr_v2"}, /* X86_FEATURE_AMD_LBR_V2 AMD Last Branch Record Extension Version 2 */
    {0x00000006, 0, 2,  0, "aperfmperf"}, /* X86_FEATURE_APERFMPERF P-State hardware coordination feedback capability (APERF/MPERF MSRs) */
    {0x00000001, 0, 2,  0, "pni"}, /* X86_FEATURE_XMM3 SSE-3 */
    {0x00000001, 0, 2,  1, "pclmulqdq"}, /* X86_FEATURE_PCLMULQDQ PCLMULQDQ instruction */
    {0x00000001, 0, 2,  2, "dtes64"}, /* X86_FEATURE_DTES64 64-bit Debug Store */
    {0x00000001, 0, 2,  3, "monitor"}, /* X86_FEATURE_MWAIT MONITOR/MWAIT support */
    {0x00000001, 0, 2,  4, "ds_cpl"}, /* X86_FEATURE_DSCPL CPL-qualified (filtered) Debug Store */
    {0x00000001, 0, 2,  5, "vmx"}, /* X86_FEATURE_VMX Hardware virtualization */
    {0x00000001, 0, 2,  6, "smx"}, /* X86_FEATURE_SMX Safer Mode eXtensions */
    {0x00000001, 0, 2,  7, "est"}, /* X86_FEATURE_EST Enhanced SpeedStep */
    {0x00000001, 0, 2,  8, "tm2"}, /* X86_FEATURE_TM2 Thermal Monitor 2 */
    {0x00000001, 0, 2,  9, "ssse3"}, /* X86_FEATURE_SSSE3 Supplemental SSE-3 */
    {0x00000001, 0, 2, 10, "cid"}, /* X86_FEATURE_CID Context ID */
    {0x00000001, 0, 2, 11, "sdbg"}, /* X86_FEATURE_SDBG Silicon Debug */
    {0x00000001, 0, 2, 12, "fma"}, /* X86_FEATURE_FMA Fused multiply-add */
    {0x00000001, 0, 2, 13, "cx16"}, /* X86_FEATURE_CX16 CMPXCHG16B instruction */
    {0x00000001, 0, 2, 14, "xtpr"}, /* X86_FEATURE_XTPR Send Task Priority Messages */
    {0x00000001, 0, 2, 15, "pdcm"}, /* X86_FEATURE_PDCM Perf/Debug Capabilities MSR */
    {0x00000001, 0, 2, 17, "pcid"}, /* X86_FEATURE_PCID Process Context Identifiers */
    {0x00000001, 0, 2, 18, "dca"}, /* X86_FEATURE_DCA Direct Cache Access */
    {0x00000001, 0, 2, 19, "sse4_1"}, /* X86_FEATURE_XMM4_1 SSE-4.1 */
    {0x00000001, 0, 2, 20, "sse4_2"}, /* X86_FEATURE_XMM4_2 SSE-4.2 */
    {0x00000001, 0, 2, 21, "x2apic"}, /* X86_FEATURE_X2APIC X2APIC */
    {0x00000001, 0, 2, 22, "movbe"}, /* X86_FEATURE_MOVBE MOVBE instruction */
    {0x00000001, 0, 2, 23, "popcnt"}, /* X86_FEATURE_POPCNT POPCNT instruction */
    {0x00000001, 0, 2, 24, "tsc_deadline_timer"}, /* X86_FEATURE_TSC_DEADLINE_TIMER TSC deadline timer */
    {0x00000001, 0, 2, 25, "aes"}, /* X86_FEATURE_AES AES instructions */
    {0x00000001, 0, 2, 26, "xsave"}, /* X86_FEATURE_XSAVE XSAVE/XRSTOR/XSETBV/XGETBV instructions */
    {0x00000001, 0, 2, 27, "osxsave"}, /* X86_FEATURE_OSXSAVE XSAVE instruction enabled in the OS */
    {0x00000001, 0, 2, 28, "avx"}, /* X86_FEATURE_AVX Advanced Vector Extensions */
    {0x00000001, 0, 2, 29, "f16c"}, /* X86_FEATURE_F16C 16-bit FP conversions */
    {0x00000001, 0, 2, 30, "rdrand"}, /* X86_FEATURE_RDRAND RDRAND instruction */
    {0x00000001, 0, 2, 31, "hypervisor"}, /* X86_FEATURE_HYPERVISOR Running on a hypervisor */
    {0xc0000001, 0, 3,  2, "rng"}, /* X86_FEATURE_XSTORE RNG present (xstore) */
    {0xc0000001, 0, 3,  3, "rng_en"}, /* X86_FEATURE_XSTORE_EN RNG enabled */
    {0xc0000001, 0, 3,  6, "ace"}, /* X86_FEATURE_XCRYPT on-CPU crypto (xcrypt) */
    {0xc0000001, 0, 3,  7, "ace_en"}, /* X86_FEATURE_XCRYPT_EN on-CPU crypto enabled */
    {0xc0000001, 0, 3,  8, "ace2"}, /* X86_FEATURE_ACE2 Advanced Cryptography Engine v2 */
    {0xc0000001, 0, 3,  9, "ace2_en"}, /* X86_FEATURE_ACE2_EN ACE v2 enabled */
    {0xc0000001, 0, 3, 10, "phe"}, /* X86_FEATURE_PHE PadLock Hash Engine */
    {0xc0000001, 0, 3, 11, "phe_en"}, /* X86_FEATURE_PHE_EN PHE enabled */
    {0xc0000001, 0, 3, 12, "pmm"}, /* X86_FEATURE_PMM PadLock Montgomery Multiplier */
    {0xc0000001, 0, 3, 13, "pmm_en"}, /* X86_FEATURE_PMM_EN PMM enabled */
    {0x80000001, 0, 2,  0, "lahf_lm"}, /* X86_FEATURE_LAHF_LM LAHF/SAHF in long mode */
    {0x80000001, 0, 2,  1, "cmp_legacy"}, /* X86_FEATURE_CMP_LEGACY If yes HyperThreading not valid */
    {0x80000001, 0, 2,  2, "svm"}, /* X86_FEATURE_SVM Secure Virtual Machine */
    {0x80000001, 0, 2,  3, "extapic"}, /* X86_FEATURE_EXTAPIC Extended APIC space */
    {0x80000001, 0, 2,  4, "cr8_legacy"}, /* X86_FEATURE_CR8_LEGACY CR8 in 32-bit mode */
    {0x80000001, 0, 2,  5, "abm"}, /* X86_FEATURE_ABM Advanced bit manipulation */
    {0x80000001, 0, 2,  6, "sse4a"}, /* X86_FEATURE_SSE4A SSE-4A */
    {0x80000001, 0, 2,  7, "misalignsse"}, /* X86_FEATURE_MISALIGNSSE Misaligned SSE mode */
    {0x80000001, 0, 2,  8, "3dnowprefetch"}, /* X86_FEATURE_3DNOWPREFETCH 3DNow prefetch instructions */
    {0x80000001, 0, 2,  9, "osvw"}, /* X86_FEATURE_OSVW OS Visible Workaround */
    {0x80000001, 0, 2, 10, "ibs"}, /* X86_FEATURE_IBS Instruction Based Sampling */
    {0x80000001, 0, 2, 11, "xop"}, /* X86_FEATURE_XOP Extended AVX instructions */
    {0x80000001, 0, 2, 12, "skinit"}, /* X86_FEATURE_SKINIT SKINIT/STGI instructions */
    {0x80000001, 0, 2, 13, "wdt"}, /* X86_FEATURE_WDT Watchdog timer */
    {0x80000001, 0, 2, 15, "lwp"}, /* X86_FEATURE_LWP Light Weight Profiling */
    {0x80000001, 0, 2, 16, "fma4"}, /* X86_FEATURE_FMA4 4 operands MAC instructions */
    {0x80000001, 0, 2, 17, "tce"}, /* X86_FEATURE_TCE Translation Cache Extension */
    {0x80000001, 0, 2, 19, "nodeid_msr"}, /* X86_FEATURE_NODEID_MSR NodeId MSR */
    {0x80000001, 0, 2, 21, "tbm"}, /* X86_FEATURE_TBM Trailing Bit Manipulations */
    {0x80000001, 0, 2, 22, "topoext"}, /* X86_FEATURE_TOPOEXT Topology extensions CPUID leafs */
    {0x80000001, 0, 2, 23, "perfctr_core"}, /* X86_FEATURE_PERFCTR_CORE Core performance counter extensions */
    {0x80000001, 0, 2, 24, "perfctr_nb"}, /* X86_FEATURE_PERFCTR_NB NB performance counter extensions */
    {0x80000001, 0, 2, 26, "bpext"}, /* X86_FEATURE_BPEXT Data breakpoint extension */
    {0x80000001, 0, 2, 27, "ptsc"}, /* X86_FEATURE_PTSC Performance time-stamp counter */
    {0x80000001, 0, 2, 28, "perfctr_llc"}, /* X86_FEATURE_PERFCTR_LLC Last Level Cache performance counter extensions */
    {0x80000001, 0, 2, 29, "mwaitx"}, /* X86_FEATURE_MWAITX MWAIT extension (MONITORX/MWAITX instructions) */
    {0x80000007, 0, 3,  9, "cpb"}, /* X86_FEATURE_CPB AMD Core Performance Boost */
    {0x00000006, 0, 2,  3, "epb"}, /* X86_FEATURE_EPB IA32_ENERGY_PERF_BIAS support */
    {0x00000010, 0, 1,  1, "cat_l3"}, /* X86_FEATURE_CAT_L3 Cache Allocation Technology L3 */
    {0x00000010, 0, 1,  2, "cat_l2"}, /* X86_FEATURE_CAT_L2 Cache Allocation Technology L2 */
    {0x00000010, 1, 2,  2, "cdp_l3"}, /* X86_FEATURE_CDP_L3 Code and Data Prioritization L3 */
    {0x80000007, 0, 3,  7, "hw_pstate"}, /* X86_FEATURE_HW_PSTATE AMD HW-PState */
    {0x80000007, 0, 3, 11, "proc_feedback"}, /* X86_FEATURE_PROC_FEEDBACK AMD ProcFeedbackInterface */
    {0x00000007, 1, 1,  0, "intel_ppin"}, /* X86_FEATURE_INTEL_PPIN Intel Processor Inventory Number */
    {0x00000010, 2, 2,  2, "cdp_l2"}, /* X86_FEATURE_CDP_L2 Code and Data Prioritization L2 */
    {0x00000010, 0, 1,  3, "mba"}, /* X86_FEATURE_MBA Memory Bandwidth Allocation */
    {0x80000008, 0, 1,  6, "mba"}, /* X86_FEATURE_MBA Memory Bandwidth Allocation */
    {0x80000022, 0, 0,  0, "perfmon_v2"}, /* X86_FEATURE_PERFMON_V2 AMD Performance Monitoring Version 2 */
    {0x8000001f, 0, 1, 31, "coherency_sfw_no"}, /* X86_FEATURE_COHERENCY_SFW_NO SNP cache coherency software work around not needed */
    {0x00000007, 0, 1,  0, "fsgsbase"}, /* X86_FEATURE_FSGSBASE RDFSBASE, WRFSBASE, RDGSBASE, WRGSBASE instructions */
    {0x00000007, 0, 1,  1, "tsc_adjust"}, /* X86_FEATURE_TSC_ADJUST TSC adjustment MSR 0x3B */
    {0x00000007, 0, 1,  2, "sgx"}, /* X86_FEATURE_SGX Software Guard Extensions */
    {0x00000007, 0, 1,  3, "bmi1"}, /* X86_FEATURE_BMI1 1st group bit manipulation extensions */
    {0x00000007, 0, 1,  4, "hle"}, /* X86_FEATURE_HLE Hardware Lock Elision */
    {0x00000007, 0, 1,  5, "avx2"}, /* X86_FEATURE_AVX2 AVX2 instructions */
    {0x00000007, 0, 1,  6, "fdp_excptn_only"}, /* X86_FEATURE_FDP_EXCPTN_ONLY FPU data pointer updated only on x87 exceptions */
    {0x00000007, 0, 1,  7, "smep"}, /* X86_FEATURE_SMEP Supervisor Mode Execution Protection */
    {0x00000007, 0, 1,  8, "bmi2"}, /* X86_FEATURE_BMI2 2nd group bit manipulation extensions */
    {0x00000007, 0, 1,  9, "erms"}, /* X86_FEATURE_ERMS Enhanced REP MOVSB/STOSB instructions */
    {0x00000007, 0, 1, 10, "invpcid"}, /* X86_FEATURE_INVPCID Invalidate Processor Context ID */
    {0x00000007, 0, 1, 11, "rtm"}, /* X86_FEATURE_RTM Restricted Transactional Memory */
    {0x00000007, 0, 1, 12, "cqm"}, /* X86_FEATURE_CQM Cache QoS Monitoring */
    {0x00000007, 0, 1, 13, "zero_fcs_fds"}, /* X86_FEATURE_ZERO_FCS_FDS Zero out FPU CS and FPU DS */
    {0x00000007, 0, 1, 14, "mpx"}, /* X86_FEATURE_MPX Memory Protection Extension */
    {0x00000007, 0, 1, 15, "rdt_a"}, /* X86_FEATURE_RDT_A Resource Director Technology Allocation */
    {0x00000007, 0, 1, 16, "avx512f"}, /* X86_FEATURE_AVX512F AVX-512 Foundation */
    {0x00000007, 0, 1, 17, "avx512dq"}, /* X86_FEATURE_AVX512DQ AVX-512 DQ (Double/Quad granular) Instructions */
    {0x00000007, 0, 1, 18, "rdseed"}, /* X86_FEATURE_RDSEED RDSEED instruction */
    {0x00000007, 0, 1, 19, "adx"}, /* X86_FEATURE_ADX ADCX and ADOX instructions */
    {0x00000007, 0, 1, 20, "smap"}, /* X86_FEATURE_SMAP Supervisor Mode Access Prevention */
    {0x00000007, 0, 1, 21, "avx512ifma"}, /* X86_FEATURE_AVX512IFMA AVX-512 Integer Fused Multiply-Add instructions */
    {0x00000007, 0, 1, 23, "clflushopt"}, /* X86_FEATURE_CLFLUSHOPT CLFLUSHOPT instruction */
    {0x00000007, 0, 1, 24, "clwb"}, /* X86_FEATURE_CLWB CLWB instruction */
    {0x00000007, 0, 1, 25, "intel_pt"}, /* X86_FEATURE_INTEL_PT Intel Processor Trace */
    {0x00000007, 0, 1, 26, "avx512pf"}, /* X86_FEATURE_AVX512PF AVX-512 Prefetch */
    {0x00000007, 0, 1, 27, "avx512er"}, /* X86_FEATURE_AVX512ER AVX-512 Exponential and Reciprocal */
    {0x00000007, 0, 1, 28, "avx512cd"}, /* X86_FEATURE_AVX512CD AVX-512 Conflict Detection */
    {0x00000007, 0, 1, 29, "sha_ni"}, /* X86_FEATURE_SHA_NI SHA1/SHA256 Instruction Extensions */
    {0x00000007, 0, 1, 30, "avx512bw"}, /* X86_FEATURE_AVX512BW AVX-512 BW (Byte/Word granular) Instructions */
    {0x00000007, 0, 1, 31, "avx512vl"}, /* X86_FEATURE_AVX512VL AVX-512 VL (128/256 Vector Length) Extensions */
    {0x0000000d, 1, 0,  0, "xsaveopt"}, /* X86_FEATURE_XSAVEOPT XSAVEOPT instruction */
    {0x0000000d, 1, 0,  1, "xsavec"}, /* X86_FEATURE_XSAVEC XSAVEC instruction */
    {0x0000000d, 1, 0,  2, "xgetbv1"}, /* X86_FEATURE_XGETBV1 XGETBV with ECX = 1 instruction */
    {0x0000000d, 1, 0,  3, "xsaves"}, /* X86_FEATURE_XSAVES XSAVES/XRSTORS instructions */
    {0x0000000d, 1, 0,  4, "xfd"}, /* X86_FEATURE_XFD eXtended Feature Disabling */
    {0x0000000f, 0, 3,  1, "cqm_llc"}, /* X86_FEATURE_CQM_LLC LLC QoS if 1 */
    {0x0000000f, 1, 3,  0, "cqm_occup_llc"}, /* X86_FEATURE_CQM_OCCUP_LLC LLC occupancy monitoring */
    {0x0000000f, 1, 3,  1, "cqm_mbm_total"}, /* X86_FEATURE_CQM_MBM_TOTAL LLC Total MBM monitoring */
    {0x0000000f, 1, 3,  2, "cqm_mbm_local"}, /* X86_FEATURE_CQM_MBM_LOCAL LLC Local MBM monitoring */
    {0x00000010, 3, 2,  0, "per_thread_mba"}, /* X86_FEATURE_PER_THREAD_MBA Per-thread Memory Bandwidth Allocation */
    {0x00000012, 0, 0,  0, "sgx1"}, /* X86_FEATURE_SGX1 Basic SGX */
    {0x00000012, 0, 0,  1, "sgx2"}, /* X86_FEATURE_SGX2 SGX Enclave Dynamic Memory Management (EDMM) */
    {0x00000007, 2, 3,  2, "rrsba_ctrl"}, /* X86_FEATURE_RRSBA_CTRL RET prediction control */
    {0x00000012, 0, 0, 11, "sgx_edeccssa"}, /* X86_FEATURE_SGX_EDECCSSA SGX EDECCSSA user leaf function */
    {0x80000020, 0, 1,  2, "smba"}, /* X86_FEATURE_SMBA Slow Memory Bandwidth Allocation */
    {0x80000020, 0, 1,  3, "bmec"}, /* X86_FEATURE_BMEC Bandwidth Monitoring Event Configuration */
    {0x00000007, 1, 0,  0, "sha512"}, /* X86_FEATURE_SHA512 SHA512 instructions */
    {0x00000007, 1, 0,  1, "sm3"}, /* X86_FEATURE_SM3 SM3 instructions */
    {0x00000007, 1, 0,  2, "sm4"}, /* X86_FEATURE_SM4 SM4 instructions */
    {0x00000007, 1, 0,  4, "avx_vnni"}, /* X86_FEATURE_AVX_VNNI AVX VNNI instructions */
    {0x00000007, 1, 0,  5, "avx512_bf16"}, /* X86_FEATURE_AVX512_BF16 AVX512 BFLOAT16 instructions */
    {0x00000007, 1, 0,  6, "lass"}, /* X86_FEATURE_LASS Linear Address Space Separation */
    {0x00000007, 1, 0,  7, "cmpccxadd"}, /* X86_FEATURE_CMPCCXADD CMPccXADD instructions */
    {0x00000007, 1, 0,  8, "arch_perfmon_ext"}, /* X86_FEATURE_ARCH_PERFMON_EXT Intel Architectural PerfMon Extension */
    {0x00000007, 1, 0, 10, "fzrm"}, /* X86_FEATURE_FZRM Fast zero-length REP MOVSB */
    {0x00000007, 1, 0, 11, "fsrs"}, /* X86_FEATURE_FSRS Fast short REP STOSB */
    {0x00000007, 1, 0, 12, "fsrc"}, /* X86_FEATURE_FSRC Fast short REP {CMPSB,SCASB} */
    {0x00000007, 1, 0, 17, "fred"}, /* X86_FEATURE_FRED Flexible Return and Event Delivery */
    {0x00000007, 1, 0, 18, "lkgs"}, /* X86_FEATURE_LKGS Like MOV_GS except MSR_KERNEL_GS_BASE = GS.base */
    {0x00000007, 1, 0, 19, "wrmsrns"}, /* X86_FEATURE_WRMSRNS Non-serializing WRMSR */
    {0x00000007, 1, 0, 21, "amx_fp16"}, /* X86_FEATURE_AMX_FP16 AMX fp16 Support */
    {0x00000007, 1, 0, 23, "avx_ifma"}, /* X86_FEATURE_AVX_IFMA Support for VPMADD52[H,L]UQ */
    {0x00000007, 1, 0, 26, "lam"}, /* X86_FEATURE_LAM Linear Address Masking */
    {0x00000007, 1, 0, 31, "movrs"}, /* X86_FEATURE_MOVRS MOVRS instructions */
    {0x80000008, 0, 1,  0, "clzero"}, /* X86_FEATURE_CLZERO CLZERO instruction */
    {0x80000008, 0, 1,  1, "irperf"}, /* X86_FEATURE_IRPERF Instructions Retired Count */
    {0x80000008, 0, 1,  2, "xsaveerptr"}, /* X86_FEATURE_XSAVEERPTR Always save/restore FP error pointers */
    {0x80000008, 0, 1,  3, "invlpgb"}, /* X86_FEATURE_INVLPGB INVLPGB and TLBSYNC instructions supported */
    {0x80000008, 0, 1,  4, "rdpru"}, /* X86_FEATURE_RDPRU Read processor register at user level */
    {0x80000008, 0, 1,  9, "wbnoinvd"}, /* X86_FEATURE_WBNOINVD WBNOINVD instruction */
    {0x80000008, 0, 1, 12, "amd_ibpb"}, /* X86_FEATURE_AMD_IBPB Indirect Branch Prediction Barrier */
    {0x80000008, 0, 1, 14, "amd_ibrs"}, /* X86_FEATURE_AMD_IBRS Indirect Branch Restricted Speculation */
    {0x80000008, 0, 1, 15, "amd_stibp"}, /* X86_FEATURE_AMD_STIBP Single Thread Indirect Branch Predictors */
    {0x80000008, 0, 1, 17, "amd_stibp_always_on"}, /* X86_FEATURE_AMD_STIBP_ALWAYS_ON Single Thread Indirect Branch Predictors always-on preferred */
    {0x80000008, 0, 1, 19, "amd_ibrs_same_mode"}, /* X86_FEATURE_AMD_IBRS_SAME_MODE Indirect Branch Restricted Speculation same mode protection */
    {0x80000008, 0, 1, 20, "efer_lmsle_mbz"}, /* X86_FEATURE_EFER_LMSLE_MBZ EFER.LMSLE must be zero */
    {0x80000008, 0, 1, 23, "amd_ppin"}, /* X86_FEATURE_AMD_PPIN Protected Processor Inventory Number */
    {0x80000008, 0, 1, 24, "amd_ssbd"}, /* X86_FEATURE_AMD_SSBD Speculative Store Bypass Disable */
    {0x80000008, 0, 1, 25, "virt_ssbd"}, /* X86_FEATURE_VIRT_SSBD Virtualized Speculative Store Bypass Disable */
    {0x80000008, 0, 1, 26, "amd_ssb_no"}, /* X86_FEATURE_AMD_SSB_NO Speculative Store Bypass is fixed in hardware. */
    {0x80000008, 0, 1, 27, "cppc"}, /* X86_FEATURE_CPPC Collaborative Processor Performance Control */
    {0x80000008, 0, 1, 28, "amd_psfd"}, /* X86_FEATURE_AMD_PSFD Predictive Store Forwarding Disable */
    {0x80000008, 0, 1, 29, "btc_no"}, /* X86_FEATURE_BTC_NO Not vulnerable to Branch Type Confusion */
    {0x80000008, 0, 1, 30, "amd_ibpb_ret"}, /* X86_FEATURE_AMD_IBPB_RET IBPB clears return address predictor */
    {0x80000008, 0, 1, 31, "brs"}, /* X86_FEATURE_BRS Branch Sampling available */
    {0x00000006, 0, 0,  0, "dtherm"}, /* X86_FEATURE_DTHERM Digital Thermal Sensor */
    {0x00000006, 0, 0,  1, "ida"}, /* X86_FEATURE_IDA Intel Dynamic Acceleration */
    {0x00000006, 0, 0,  2, "arat"}, /* X86_FEATURE_ARAT Always Running APIC Timer */
    {0x00000006, 0, 0,  4, "pln"}, /* X86_FEATURE_PLN Intel Power Limit Notification */
    {0x00000006, 0, 0,  6, "pts"}, /* X86_FEATURE_PTS Intel Package Thermal Status */
    {0x00000006, 0, 0,  7, "hwp"}, /* X86_FEATURE_HWP Intel Hardware P-states */
    {0x00000006, 0, 0,  8, "hwp_notify"}, /* X86_FEATURE_HWP_NOTIFY HWP Notification */
    {0x00000006, 0, 0,  9, "hwp_act_window"}, /* X86_FEATURE_HWP_ACT_WINDOW HWP Activity Window */
    {0x00000006, 0, 0, 10, "hwp_epp"}, /* X86_FEATURE_HWP_EPP HWP Energy Perf. Preference */
    {0x00000006, 0, 0, 11, "hwp_pkg_req"}, /* X86_FEATURE_HWP_PKG_REQ HWP Package Level Request */
    {0x00000006, 0, 0, 15, "hwp_highest_perf_change"}, /* X86_FEATURE_HWP_HIGHEST_PERF_CHANGE HWP Highest perf change */
    {0x00000006, 0, 0, 19, "hfi"}, /* X86_FEATURE_HFI Hardware Feedback Interface */
    {0x8000000a, 0, 3,  0, "npt"}, /* X86_FEATURE_NPT Nested Page Table support */
    {0x8000000a, 0, 3,  1, "lbrv"}, /* X86_FEATURE_LBRV LBR Virtualization support */
    {0x8000000a, 0, 3,  2, "svm_lock"}, /* X86_FEATURE_SVML SVM locking MSR */
    {0x8000000a, 0, 3,  3, "nrip_save"}, /* X86_FEATURE_NRIPS SVM next_rip save */
    {0x8000000a, 0, 3,  4, "tsc_scale"}, /* X86_FEATURE_TSCRATEMSR TSC scaling support */
    {0x8000000a, 0, 3,  5, "vmcb_clean"}, /* X86_FEATURE_VMCBCLEAN VMCB clean bits support */
    {0x8000000a, 0, 3,  6, "flushbyasid"}, /* X86_FEATURE_FLUSHBYASID Flush-by-ASID support */
    {0x8000000a, 0, 3,  7, "decodeassists"}, /* X86_FEATURE_DECODEASSISTS Decode Assists support */
    {0x8000000a, 0, 3, 10, "pausefilter"}, /* X86_FEATURE_PAUSEFILTER Filtered pause intercept */
    {0x8000000a, 0, 3, 12, "pfthreshold"}, /* X86_FEATURE_PFTHRESHOLD Pause filter threshold */
    {0x8000000a, 0, 3, 13, "avic"}, /* X86_FEATURE_AVIC Virtual Interrupt Controller */
    {0x8000000a, 0, 3, 15, "v_vmsave_vmload"}, /* X86_FEATURE_V_VMSAVE_VMLOAD Virtual VMSAVE VMLOAD */
    {0x8000000a, 0, 3, 16, "vgif"}, /* X86_FEATURE_VGIF Virtual GIF */
    {0x8000000a, 0, 3, 17, "gmet"}, /* X86_FEATURE_GMET Guest Mode Execution Trap */
    {0x8000000a, 0, 3, 18, "x2avic"}, /* X86_FEATURE_X2AVIC Virtual x2apic */
    {0x8000000a, 0, 3, 20, "v_spec_ctrl"}, /* X86_FEATURE_V_SPEC_CTRL Virtual SPEC_CTRL */
    {0x8000000a, 0, 3, 25, "vnmi"}, /* X86_FEATURE_VNMI Virtual NMI */
    {0x8000000a, 0, 3, 28, "svme_addr_chk"}, /* X86_FEATURE_SVME_ADDR_CHK SVME addr check */
    {0x8000000a, 0, 3, 29, "bus_lock_threshold"}, /* X86_FEATURE_BUS_LOCK_THRESHOLD Bus lock threshold */
    {0x8000000a, 0, 3, 30, "idle_hlt"}, /* X86_FEATURE_IDLE_HLT IDLE HLT intercept */
    {0x00000007, 0, 2,  1, "avx512vbmi"}, /* X86_FEATURE_AVX512VBMI AVX512 Vector Bit Manipulation instructions */
    {0x00000007, 0, 2,  2, "umip"}, /* X86_FEATURE_UMIP User Mode Instruction Protection */
    {0x00000007, 0, 2,  3, "pku"}, /* X86_FEATURE_PKU Protection Keys for Userspace */
    {0x00000007, 0, 2,  4, "ospke"}, /* X86_FEATURE_OSPKE OS Protection Keys Enable */
    {0x00000007, 0, 2,  5, "waitpkg"}, /* X86_FEATURE_WAITPKG UMONITOR/UMWAIT/TPAUSE Instructions */
    {0x00000007, 0, 2,  6, "avx512_vbmi2"}, /* X86_FEATURE_AVX512_VBMI2 Additional AVX512 Vector Bit Manipulation Instructions */
    {0x00000007, 0, 2,  7, "shstk"}, /* X86_FEATURE_SHSTK Shadow stack */
    {0x00000007, 0, 2,  8, "gfni"}, /* X86_FEATURE_GFNI Galois Field New Instructions */
    {0x00000007, 0, 2,  9, "vaes"}, /* X86_FEATURE_VAES Vector AES */
    {0x00000007, 0, 2, 10, "vpclmulqdq"}, /* X86_FEATURE_VPCLMULQDQ Carry-Less Multiplication Double Quadword */
    {0x00000007, 0, 2, 11, "avx512_vnni"}, /* X86_FEATURE_AVX512_VNNI Vector Neural Network Instructions */
    {0x00000007, 0, 2, 12, "avx512_bitalg"}, /* X86_FEATURE_AVX512_BITALG Support for VPOPCNT[B,W] and VPSHUF-BITQMB instructions */
    {0x00000007, 0, 2, 13, "tme"}, /* X86_FEATURE_TME Intel Total Memory Encryption */
    {0x00000007, 0, 2, 14, "avx512_vpopcntdq"}, /* X86_FEATURE_AVX512_VPOPCNTDQ POPCNT for vectors of DW/QW */
    {0x00000007, 0, 2, 16, "la57"}, /* X86_FEATURE_LA57 5-level page tables */
    {0x00000007, 0, 2, 22, "rdpid"}, /* X86_FEATURE_RDPID RDPID instruction */
    {0x00000007, 0, 2, 24, "bus_lock_detect"}, /* X86_FEATURE_BUS_LOCK_DETECT Bus Lock detect */
    {0x00000007, 0, 2, 25, "cldemote"}, /* X86_FEATURE_CLDEMOTE CLDEMOTE instruction */
    {0x00000007, 0, 2, 27, "movdiri"}, /* X86_FEATURE_MOVDIRI MOVDIRI instruction */
    {0x00000007, 0, 2, 28, "movdir64b"}, /* X86_FEATURE_MOVDIR64B MOVDIR64B instruction */
    {0x00000007, 0, 2, 29, "enqcmd"}, /* X86_FEATURE_ENQCMD ENQCMD and ENQCMDS instructions */
    {0x00000007, 0, 2, 30, "sgx_lc"}, /* X86_FEATURE_SGX_LC Software Guard Extensions Launch Control */
    {0x80000007, 0, 1,  0, "overflow_recov"}, /* X86_FEATURE_OVERFLOW_RECOV MCA overflow recovery support */
    {0x80000007, 0, 1,  1, "succor"}, /* X86_FEATURE_SUCCOR Uncorrectable error containment and recovery */
    {0x80000007, 0, 3, 16, "cppc_perf_prio"}, /* X86_FEATURE_CPPC_PERF_PRIO CPPC Floor Perf support */
    {0x80000007, 0, 1,  3, "smca"}, /* X86_FEATURE_SMCA Scalable MCA */
    {0x00000007, 0, 3,  2, "avx512_4vnniw"}, /* X86_FEATURE_AVX512_4VNNIW AVX-512 Neural Network Instructions */
    {0x00000007, 0, 3,  3, "avx512_4fmaps"}, /* X86_FEATURE_AVX512_4FMAPS AVX-512 Multiply Accumulation Single precision */
    {0x00000007, 0, 3,  4, "fsrm"}, /* X86_FEATURE_FSRM Fast Short Rep Mov */
    {0x00000007, 0, 3,  8, "avx512_vp2intersect"}, /* X86_FEATURE_AVX512_VP2INTERSECT AVX-512 Intersect for D/Q */
    {0x00000007, 0, 3,  9, "srbds_ctrl"}, /* X86_FEATURE_SRBDS_CTRL SRBDS mitigation MSR available */
    {0x00000007, 0, 3, 10, "md_clear"}, /* X86_FEATURE_MD_CLEAR VERW clears CPU buffers */
    {0x00000007, 0, 3, 11, "rtm_always_abort"}, /* X86_FEATURE_RTM_ALWAYS_ABORT RTM transaction always aborts */
    {0x00000007, 0, 3, 13, "tsx_force_abort"}, /* X86_FEATURE_TSX_FORCE_ABORT TSX_FORCE_ABORT */
    {0x00000007, 0, 3, 14, "serialize"}, /* X86_FEATURE_SERIALIZE SERIALIZE instruction */
    {0x00000007, 0, 3, 15, "hybrid_cpu"}, /* X86_FEATURE_HYBRID_CPU This part has CPUs of more than one type */
    {0x00000007, 0, 3, 16, "tsxldtrk"}, /* X86_FEATURE_TSXLDTRK TSX Suspend Load Address Tracking */
    {0x00000007, 0, 3, 18, "pconfig"}, /* X86_FEATURE_PCONFIG Intel PCONFIG */
    {0x00000007, 0, 3, 19, "arch_lbr"}, /* X86_FEATURE_ARCH_LBR Intel ARCH LBR */
    {0x00000007, 0, 3, 20, "ibt"}, /* X86_FEATURE_IBT Indirect Branch Tracking */
    {0x00000007, 0, 3, 22, "amx_bf16"}, /* X86_FEATURE_AMX_BF16 AMX bf16 Support */
    {0x00000007, 0, 3, 23, "avx512_fp16"}, /* X86_FEATURE_AVX512_FP16 AVX512 FP16 */
    {0x00000007, 0, 3, 24, "amx_tile"}, /* X86_FEATURE_AMX_TILE AMX tile Support */
    {0x00000007, 0, 3, 25, "amx_int8"}, /* X86_FEATURE_AMX_INT8 AMX int8 Support */
    {0x00000007, 0, 3, 26, "spec_ctrl"}, /* X86_FEATURE_SPEC_CTRL Speculation Control (IBRS + IBPB) */
    {0x00000007, 0, 3, 27, "intel_stibp"}, /* X86_FEATURE_INTEL_STIBP Single Thread Indirect Branch Predictors */
    {0x00000007, 0, 3, 28, "flush_l1d"}, /* X86_FEATURE_FLUSH_L1D Flush L1D cache */
    {0x00000007, 0, 3, 29, "arch_capabilities"}, /* X86_FEATURE_ARCH_CAPABILITIES IA32_ARCH_CAPABILITIES MSR (Intel) */
    {0x00000007, 0, 3, 30, "core_capabilities"}, /* X86_FEATURE_CORE_CAPABILITIES IA32_CORE_CAPABILITIES MSR */
    {0x00000007, 0, 3, 31, "spec_ctrl_ssbd"}, /* X86_FEATURE_SPEC_CTRL_SSBD Speculative Store Bypass Disable */
    {0x8000001f, 0, 0,  0, "sme"}, /* X86_FEATURE_SME Secure Memory Encryption */
    {0x8000001f, 0, 0,  1, "sev"}, /* X86_FEATURE_SEV Secure Encrypted Virtualization */
    {0x8000001f, 0, 0,  2, "vm_page_flush"}, /* X86_FEATURE_VM_PAGE_FLUSH VM Page Flush MSR is supported */
    {0x8000001f, 0, 0,  3, "sev_es"}, /* X86_FEATURE_SEV_ES Secure Encrypted Virtualization - Encrypted State */
    {0x8000001f, 0, 0,  4, "sev_snp"}, /* X86_FEATURE_SEV_SNP Secure Encrypted Virtualization - Secure Nested Paging */
    {0x8000001f, 0, 0,  8, "snp_secure_tsc"}, /* X86_FEATURE_SNP_SECURE_TSC SEV-SNP Secure TSC */
    {0x8000001f, 0, 0,  9, "v_tsc_aux"}, /* X86_FEATURE_V_TSC_AUX Virtual TSC_AUX */
    {0x8000001f, 0, 0, 10, "sme_coherent"}, /* X86_FEATURE_SME_COHERENT hardware-enforced cache coherency */
    {0x8000001f, 0, 0, 14, "debug_swap"}, /* X86_FEATURE_DEBUG_SWAP SEV-ES full debug state swap support */
    {0x8000001f, 0, 0, 21, "rmpread"}, /* X86_FEATURE_RMPREAD RMPREAD instruction */
    {0x8000001f, 0, 0, 23, "segmented_rmp"}, /* X86_FEATURE_SEGMENTED_RMP Segmented RMP support */
    {0x8000001f, 0, 0, 27, "allowed_sev_features"}, /* X86_FEATURE_ALLOWED_SEV_FEATURES Allowed SEV Features */
    {0x8000001f, 0, 0, 28, "svsm"}, /* X86_FEATURE_SVSM SVSM present */
    {0x8000001f, 0, 0, 30, "hv_inuse_wr_allowed"}, /* X86_FEATURE_HV_INUSE_WR_ALLOWED Allow Write to in-use hypervisor-owned pages */
    {0x80000021, 0, 0,  0, "no_nested_data_bp"}, /* X86_FEATURE_NO_NESTED_DATA_BP No Nested Data Breakpoints */
    {0x80000021, 0, 0,  1, "wrmsr_xx_base_ns"}, /* X86_FEATURE_WRMSR_XX_BASE_NS WRMSR to {FS,GS,KERNEL_GS}_BASE is non-serializing */
    {0x80000021, 0, 0,  2, "lfence_rdtsc"}, /* X86_FEATURE_LFENCE_RDTSC LFENCE always serializing / synchronizes RDTSC */
    {0x80000021, 0, 0,  5, "verw_clear"}, /* X86_FEATURE_VERW_CLEAR The memory form of VERW mitigates TSA */
    {0x80000021, 0, 0,  6, "null_sel_clr_base"}, /* X86_FEATURE_NULL_SEL_CLR_BASE Null Selector Clears Base */
    {0x80000021, 0, 0,  8, "autoibrs"}, /* X86_FEATURE_AUTOIBRS Automatic IBRS */
    {0x80000021, 0, 0,  9, "no_smm_ctl_msr"}, /* X86_FEATURE_NO_SMM_CTL_MSR SMM_CTL MSR is not present */
    {0x80000021, 0, 0, 17, "gp_on_user_cpuid"}, /* X86_FEATURE_GP_ON_USER_CPUID User CPUID faulting */
    {0x80000021, 0, 0, 20, "prefetchi"}, /* X86_FEATURE_PREFETCHI Prefetch Data/Instruction to Cache Level */
    {0x80000021, 0, 0, 23, "avx512_bmm"}, /* X86_FEATURE_AVX512_BMM AVX512 Bit Matrix Multiply instructions */
    {0x80000021, 0, 0, 24, "eraps"}, /* X86_FEATURE_ERAPS Enhanced Return Address Predictor Security */
    {0x80000021, 0, 0, 27, "sbpb"}, /* X86_FEATURE_SBPB Selective Branch Prediction Barrier */
    {0x80000021, 0, 0, 28, "ibpb_brtype"}, /* X86_FEATURE_IBPB_BRTYPE MSR_PRED_CMD[IBPB] flushes all branch type predictions */
    {0x80000021, 0, 0, 29, "srso_no"}, /* X86_FEATURE_SRSO_NO CPU is not affected by SRSO */
    {0x80000021, 0, 0, 30, "srso_user_kernel_no"}, /* X86_FEATURE_SRSO_USER_KERNEL_NO CPU is not affected by SRSO across user/kernel boundaries */
    {0x80000021, 0, 0, 31, "srso_bp_spec_reduce"}, /* X86_FEATURE_SRSO_BP_SPEC_REDUCE srso_bp_spec_reduce */
    {0x80000022, 0, 0,  2, "amd_lbr_pmc_freeze"}, /* X86_FEATURE_AMD_LBR_PMC_FREEZE AMD LBR and PMC Freeze */
    {0x00000007, 2, 3,  4, "bhi_ctrl"}, /* X86_FEATURE_BHI_CTRL BHI_DIS_S HW control available */
    {0x80000007, 0, 3, 15, "amd_fast_cppc"}, /* X86_FEATURE_AMD_FAST_CPPC Fast CPPC */
    {0x80000026, 0, 0, 30, "amd_htr_cores"}, /* X86_FEATURE_AMD_HTR_CORES Heterogeneous Core Topology */
    {0x80000021, 0, 0, 22, "amd_workload_class"}, /* X86_FEATURE_AMD_WORKLOAD_CLASS Workload Classification */
    {0x00000007, 1, 3, 21, "apx"}, /* X86_FEATURE_APX Advanced Performance Extensions */
    {0x80000021, 0, 2,  1, "tsa_sq_no"}, /* X86_FEATURE_TSA_SQ_NO AMD CPU not vulnerable to TSA-SQ */
    {0x80000021, 0, 2,  2, "tsa_l1_no"}, /* X86_FEATURE_TSA_L1_NO AMD CPU not vulnerable to TSA-L1 */
    {0x80000020, 0, 1,  5, "abmc"}, /* X86_FEATURE_ABMC Assignable Bandwidth Monitoring Counters */
    {0x00000007, 1, 2,  5, "msr_imm"}, /* X86_FEATURE_MSR_IMM MSR immediate form instructions */
    {0x00000012, 0, 0, 10, "sgx_eupdatesvn"}, /* X86_FEATURE_SGX_EUPDATESVN Support for ENCLS[EUPDATESVN] instruction */
    {0x80000020, 0, 1,  6, "sdciae"}, /* X86_FEATURE_SDCIAE L3 Smart Data Cache Injection Allocation Enforcement */
    {0x8000000a, 0, 2,  6, "x2avic_ext"}, /* X86_FEATURE_X2AVIC_EXT AMD SVM x2AVIC support for 4k vCPUs */
};
static const unsigned cpuid_flags_count = 336;

/* 336 CPUID-derived flags, 24 unique leaves */
